version: '1.0'

services:
  db:
    container_name: video-posting-db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - video-posting-network
    restart: unless-stopped

networks:
  video-posting-network:
    driver: bridge

volumes:
  db:
